"""エグゼキューター用定数"""

# UI要素取得のデフォルト設定
DEFAULT_UI_MAX_DEPTH = 3
DEFAULT_UI_ELEMENTS_TIMEOUT = 10  # 秒
DEFAULT_CLICK_ELEMENT_TIMEOUT = 5  # 秒
DEFAULT_FOCUS_ELEMENT_TIMEOUT = 5  # 秒

# スクリーンショットのデフォルト設定
DEFAULT_SCREENSHOT_QUALITY = 85
DEFAULT_HIGHLIGHT_RADIUS = 15
